# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Resource
version:      0.01
version_from: lib/WWW/Resource.pm
installdirs:  site
requires:
    FCGI:                          0
    HTTP::Status:                  0
    JSON:                          0
    XML::Dumper:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
